In [1]:
import pandas
from uuid import uuid4
import random
from datetime import date
from dateutil.relativedelta import relativedelta

In [2]:
# maps 
territory_map = {
    "t1": "North",
    "t2": "South",
    "t3": "West",
    "t4": "East"
}

seller_map = {
    "u1": "John Doe",
    "u2": "Jane Doe",
    "u3": "Bill Tack",
    "u4": "Peter Martin",
    "u5": "Michael Block",
    "u6": "Denise Waters",
    "u7": "Anna White",
    "u8": "Mia Sears",
    "u9": "Daniel Metters",
    "u0": "Lina Sanders",
}

In [3]:
n_samples_transactions = 1000

uuids = [str(uuid4()) for _ in range(n_samples_transactions)]

territories = random.choices(list(territory_map.keys()), k=n_samples_transactions)
sellers = random.choices(list(seller_map.keys()), k=n_samples_transactions)
amounts = [round(random.random()*10_000, 2) for _ in range(n_samples_transactions)]

# compute random days between Jan 1st, 2023 and June 30th, 2026
# by creating random offsets from the initial date, bounded to the end date
date_ini = date(2023, 1, 1)
date_end = date(2026, 6, 30)
date_diff_days = (date_end - date_ini).days
index_dates = range(0, date_diff_days+1)
days_offset = random.choices(index_dates, k=n_samples_transactions)

# some days (2/7) are weekends, so to make it more realistic
# we pick a random set with replacement from those days we know are week days
# and paste them together
random_dates = [date_ini + relativedelta(days=day_offset) for day_offset in days_offset]
week_days = [d for d in random_dates if d.isoweekday() < 6]
transaction_dates = week_days + random.choices(week_days, k=n_samples_transactions - len(week_days))

In [4]:
from IPython.display import display, HTML
transaction_df = pandas.DataFrame(
    {
        "transaction_id": uuids,
        "transaction_date": transaction_dates,
        "seller_id": sellers,
        "amount_eur": amounts
    }
)
seller_df = pandas.DataFrame({
    "seller_id": seller_map.keys(),
    "seller_name": seller_map.values(),
})

territory_df = pandas.DataFrame({
    "territory_id": territory_map.keys(),
    "territory_name": territory_map.values(),
})

display(HTML(transaction_df.head().to_html(index=False)))
display(HTML(seller_df.head().to_html(index=False)))
display(HTML(territory_df.head().to_html(index=False)))

In [5]:
transaction_df.to_csv("./transactions.csv", index=False)
seller_df.to_csv("./seller.csv", index=False)
territory_df.to_csv("./territory.csv", index=False)